baseURL = 'https://honoraiteam.github.io/'

title = '荣耀AI团队'
theme = 'LoveIt'

languageCode = 'zh-CN'
languageName = "简体中文"
hasCJKLanguage = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'